apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-statefulset
  name: test-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-statefulset
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      containers:
      - image: doesnotexist/definitelydoesntexist
        name: willfail
