apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: invalid
subjects:
- kind: Group
  name: admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # invalid roleRef to fail test - roleRef should reference a ClusterRole, not a Role
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
