---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-configmap
  labels:
    app: {{ include "test-capabilities.name" . }}
    name: {{ include "test-capabilities.name" . }}
data:
  should: "always exist" 
---
{{ if eq .Capabilities.KubeVersion.Version "v1.42.0" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeversion-configmap
  labels:
    app: {{ include "test-capabilities.name" . }}
    name: {{ include "test-capabilities.name" . }}
data:
  should: "only when kubeversion is equals v1.42.0"
{{- end }}
---
{{ if $.Capabilities.APIVersions.Has "foo.bar/v1" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apiversions-configmap
  labels:
    app: {{ include "test-capabilities.name" . }}
    name: {{ include "test-capabilities.name" . }}
data:
  should: "only when a the fake apiVersion is set"
{{- end }}